# -*- coding: utf-8 -*-
"""NeuralNetwork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19C7soH9vUoxmoxk6Mr98-4pu_uV0ylxj
"""

import torch
import torch.nn as nn
from torch.nn import functional as F

class Position_wise_FFN(nn.Module):
  def __init__(self, dim, dropout):
    super(Position_wise_FFN,self).__init__() # A usual way to define an layer using API: https://pytorch.org/docs/stable/generated/torch.nn.Sequential.html
    self.FFN = nn.Sequential(
        nn.Linear(dim,4*dim),
        nn.ReLU(),
        nn.Linear(4*dim,dim),
        nn.Dropout(dropout)
    )

  def forward(self,x):
    return self.FFN(x)